apiVersion: apps/v1
kind: Deployment
metadata:
  name: metget-api
  namespace: metget
  labels:
    app.kubernetes.io/name: metget-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metget-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metget-api
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - image: zcobell/metget-api:0.0.1
        imagePullPolicy: Always
        name: metget-api
        env:
        - name: METGET_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: metget-database-secret
              key: username  
        - name: METGET_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metget-database-secret
              key: password
        - name: METGET_DATABASE
          valueFrom:
            configMapKeyRef:
              name: metget-configmap
              key: database.name
        - name: METGET_REQUEST_TABLE
          valueFrom:
            configMapKeyRef:
              name: metget-configmap
              key: database.request_table
        - name: METGET_API_KEY_TABLE
          valueFrom:
            configMapKeyRef:
              name: metget-configmap
              key: database.apikey_table
        - name: METGET_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: metget-configmap
              key: s3.storage_bucket
        - name: METGET_S3_BUCKET_UPLOAD
          valueFrom:
            configMapKeyRef:
              name: metget-configmap
              key: s3.upload_bucket 
        - name: METGET_RABBITMQ_QUEUE
          valueFrom:
            configMapKeyRef:
              name: metget-configmap
              key: rabbit.queue 
        - name: METGET_ENFORCE_CREDIT_LIMITS
          value: "true"
        ports:
        - name: metget-api-port
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metget-api
  namespace: metget
  labels: 
    app.kubernetes.io/name: metget-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: metget-api-port
      protocol: TCP
  selector:
    app.kubernetes.io/name: metget-api
