apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: metget-build-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: metget-build-dependency
      eventSourceName: metget-build-source
      eventName: metget-queue-source
  triggers:
    - template:
        name: metget-build-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: metget-build-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      # value will get overridden by the event payload
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: metget-build-dependency
                dataKey: body
              dest: spec.arguments.parameters.0.value
