apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: metget-rabbitmq-controller
  namespace: metget
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
          - containerPort: 5672
          - containerPort: 15672
        resources:
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: metget-rabbitmq-service
  namespace: metget
spec:
  ports:
    - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq
