apiVersion: v1
kind: PersistentVolume
metadata:
  name: metget-database-pv-volume
  namespace: metget
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-047908959a2d5c824
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metget-database-pv-claim
  namespace: metget
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
